[package]
name = "every_match_responder"
version = "0.1.0"
authors = ["Christian Gracia <christiangracia.student@careerdevs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
